image: bitriseio/docker-android:v2019_11_09-08_04-b1834
# you can find latest docker image at https://hub.docker.com/r/bitriseio/docker-android/tags
# to ensure backward compatability we should always use a concrete docker image version and NOT latest!

variables:
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle

cache:
  key: $CI_PROJECT_NAME
  paths:
    - .gradle/wrapper
    - .gradle/caches

merge_request:
  stage: test
  artifacts:
    when: always
    expire_in: 3 days
    paths:
      - "*/build/reports"
  tags:
    - docker
    - x86
  only:
    - merge_requests
  script:
    - ./gradlew clean testDebugUnitTest lintDebug assembleDebug
