import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/jmfayard/refreshVersions
 */
object Libs {
    const val appcompat: String = "androidx.appcompat:appcompat:_"

    const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:_"

    const val core_ktx: String = "androidx.core:core-ktx:_"

    const val espresso_core: String = "androidx.test.espresso:espresso-core:_"

    const val androidx_test_ext_junit: String = "androidx.test.ext:junit:_"

    const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:_"

    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:_"

    const val material: String = "com.google.android.material:material:_"

    const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    const val junit_junit: String = "junit:junit:_"

    const val org_jacoco_ant: String = "org.jacoco:org.jacoco.ant:_"

    const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:_"
}
